apiVersion: v1
kind: Pod
metadata:
  name: disk-filler-2
spec:
  containers:
  - name: disk-consumer
    image: busybox
    command:
    - sh
    - -c
    - |
      dd if=/dev/zero of=/tmp/bigfile2 bs=1M count=100
      sleep 3600
    volumeMounts:
    - name: host-tmp
      mountPath: /tmp
  volumes:
  - name: host-tmp
    hostPath:
      path: /tmp