apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  tolerations:
  - key: "example.com/no-schedule"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: app
    image: nginx:alpine