apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: resource-test
  template:
    metadata:
      labels:
        app: resource-test
    spec:
      containers:
      - name: app
        image: nginx:alpine
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"