apiVersion: v1
kind: Pod
metadata:
  name: compliant-pod
  namespace: limitrange-test
spec:
  containers:
  - name: app
    image: nginx:alpine
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"