apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-hog-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: resource-hog
  template:
    metadata:
      labels:
        app: resource-hog
    spec:
      containers:
      - name: cpu-memory-hog
        image: progrium/stress
        args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "128M"]
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"