apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: default
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "2Gi"
    limits.cpu: "2000m"
    limits.memory: "4Gi"
    pods: "20"